### ISSUE TITLE
python可以成功获取得到，要先安装库

### ISSUE THREAD

**Issue by lanyucomputer** [huaisha1224/Get_JDCookie#2]
这个是安装库的命令
 pip install pyppeteer
 pip install pyperclip
这个程序是不是又重新下载了Chromium内核 新的浏览器了，有137M,可以直接调用系统安装 的CHROME浏览器吗

**Comment by lanyucomputer** [comment]
asyncio.get_event_loop().run_until_complete(main()) #调用
[INFO] Starting Chromium download.
请在弹出的网页中登录账号、推荐使用账户短信验证码的形式登录。
100%|██████████| 137M/137M [00:10<00:00, 12.8Mb/s]
[INFO] Beginning extraction
[INFO] Chromium extracted to:

**Comment by huaisha1224** [comment]
pyppeteer这个自动化工具不同于selenium可以调用自带的浏览器、是需要安装自己的Chromium浏览器的
