### ISSUE TITLE
生成exe大小不对只有6.5M

### ISSUE THREAD

**Issue by LinHtao** [huaisha1224/Get_JDCookie#4]
请问修改了代码后，怎么重新生成exe ，执行pyinstaller -F Get-JDCookie.py并不能达到像你那样的效果

**Comment by huaisha1224** [comment]
我创建了一个version_info.txt文件
然后在打包的时候指定了这个文件和ico 其他的就和你上面写的指令是一样的了。
pyinstaller -F -i favicon.ico --version-file=version_info.txt  Get-JDCookie.py

**Comment by LinHtao** [comment]
> 我创建了一个version_info.txt文件 然后在打包的时候指定了这个文件和ico 其他的就和你上面写的指令是一样的了。 pyinstaller -F -i favicon.ico --version-file=version_info.txt Get-JDCookie.py
首先感谢作者的回复，我见你生成的exe有28.6MB，并且你的exe可以检测是否有安装谷歌内核。我执行完编译指令后生成的exe只有6.5MB，打开是黑窗口闪退的，请问大概看得出什么原因吗？感觉是库没打包上去？感谢！

**Comment by huaisha1224** [comment]
你先在Python环境中运行一下Get-JDCookie.py 看看功能是否正常
我有点怀疑是你的模块没有安装、所以在生成exe的时候 模块没有打包进去。

**Comment by LinHtao** [comment]
> 你先在Python环境中运行一下Get-JDCookie.py 看看功能是否正常 我有点怀疑是你的模块没有安装、所以在生成exe的时候 模块没有打包进去。

是的，我看生成exe大小，也是怀疑模块没打包进去，但是用IDEA，python环境运行后正常
