### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by simplesafe** [huaisha1224/Get_JDCookie#6]
https://home.m.jd.com/userinfom/QueryUserInfoM 该网址显示 403 Forbidden
![image](https://github.com/huaisha1224/Get_JDCookie/assets/37205922/daf66195-2d6f-44ff-8d97-45dea23dddd1)

**Comment by huaisha1224** [comment]
今天修正了JD登录页面403的问题，可以更新代码之后重新泡一下。

**Comment by 410252889** [comment]
可以提供打包好的 exe文件吗  release里面没有更新

**Comment by huaisha1224** [comment]
我提交release了
https://github.com/huaisha1224/Get_JDCookie/releases/
