### ISSUE TITLE
win11 报毒啊

### ISSUE THREAD

**Issue by T1-ong** [huaisha1224/Get_JDCookie#9]
啥情况

**Comment by T1-ong** [comment]
类型:木马-Win64/Trojan.Generic.HgEATQYA
描述:木马是一种伪装成正常文件的恶意软件，会盗取您的帐号、密码等隐私资料。
扫描引擎:云安全引擎
文件路径:C:\Users\sun\Desktop\Get_JDCookie-main\exe\Get-JDCookie.exe
文件大小:6.92M (7,260,632 字节)
文件版本:2023, 12, 27, 1
文件描述:京东Cookie获取工具
文件指纹（MD5）:b1116493af3e9e0fc4afa04d139643b8
处理建议:隔离文件

**Comment by huaisha1224** [comment]
这是一个很简单的工具，如果不放心的话可以用源码运行的
